[project]
name = "react-langchain-ecommerce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ashwinfelix", email = "ashwinfelixmanoj@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "black>=26.5.1",
    "isort>=8.0.1",
    "langchain>=1.3.14",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.4.3",
    "python-dotenv>=1.2.2",
]

[project.scripts]
react-langchain-ecommerce = "react_langchain_ecommerce:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
